#!/usr/bin/env bash

# Prompt user to delete local branches with no upstream

for branch in $(git for-each-ref --format="%(refname:short)" refs/heads)
do
  upstream=$(git rev-parse --abbrev-ref $branch@{upstream} 2>/dev/null)
  if [[ $? != 0 ]]; then
    read -r -p "Are you sure you want to delete $branch? [y/N] " response
    if [[ $response == "y" || $response == "Y" ]]
    then
      git branch -D $branch
    fi
  fi
done
