#!/bin/bash

#######################################
# Figures out the directory of the file in which it is invoked.
# Credit goes to http://www.ostricher.com/2014/10/the-right-way-to-get-the-directory-of-a-bash-script/
#######################################
get_script_dir() {
  local source="${BASH_SOURCE[0]}"
  # While $source is a symlink, resolve it
  while [[ -h "$source" ]]; do
    local dir="$( cd -P "$( dirname "$source" )" && pwd )"
    source="$( readlink "$source" )"
    # If $source was a relative symlink (so no "/" as prefix, need to resolve it relative to the symlink base directory
    [[ $source != /* ]] && source="$dir/$source"
  done
  dir="$( cd -P "$( dirname "$source" )" && pwd )"
  echo "$dir"
}

readonly PARENT_DIR="$(get_script_dir)"
readonly REPO_ROOT="$PARENT_DIR/../.."

source "$PARENT_DIR/../../lib/functions.bash"

# Homebrew
export PATH="$PATH:/usr/local/sbin"
# Python
export PATH="$PATH:$HOME/Library/Python/3.6/bin"
# https://github.com/bachand/battlestation
export PATH="$PATH:$REPO_ROOT/bin:$REPO_ROOT/script"
# VS Code
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
# https://github.com/apple/swift
export PATH="$PATH:/Applications/CMake.app/Contents/bin"

# only source .bashrc if we are interactive
case "$-" in
*i*)
  [[ -r ~/.bashrc ]] && source ~/.bashrc
  ;;
esac

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

if hash rbenv 2>/dev/null
then
  eval "$(rbenv init -)"
fi
