#!/bin/bash

# These should move to `.profile` (which has yet to be made)
export PATH="$HOME/Library/Python/3.6/bin:$PATH" # Python
export PATH="/usr/local/sbin:$PATH" # Homebrew
export PATH="/Applications/CMake.app/Contents/bin:$PATH" # for compiling swift repo

# only source .bashrc if we are interactive
case "$-" in
*i*)
  [[ -r ~/.bashrc ]] && source ~/.bashrc
  ;;
esac

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

if hash rbenv 2>/dev/null
then
  eval "$(rbenv init -)"
fi
