#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/battlestation/utils'
require_relative '../lib/output'

# A script for removing personally identified information from files.

PROGRAM_NAME = "#{File.basename(__FILE__)}"

if ARGV.count != 1
  Output.put_info("Usage: #{PROGRAM_NAME} path")
  exit 1
end

path = ARGV[0]

unless File.exist?(path)
  Battlestation::Utils.exit_on_error("'#{path}' does not exist")
end

if File.directory?(path)
  Battlestation::Utils.exit_on_error("'#{path}' must be a file")
end

`exiftool "#{path}" >/dev/null 2>&1;`

if $?.exitstatus != 0
  Battlestation::Utils.exit_on_error("#{PROGRAM_NAME} only supports images 😢. Stay tuned 📺")
else
  system 'bash', '-c', %{
orientation_value=$(exiftool -s -s -s -orientation "#{path}")
exiftool -all= "#{path}"
exiftool -orientation="$orientation_value" "#{path}"
}

  if $?.exitstatus != 0
    Battlestation::Utils.exit_on_error("Error anonymizing '#{path}'")
  end
end
