#!/usr/bin/env ruby
# frozen_string_literal: true

# A simple way to save a file to an S3 bucket. This script assumes that AWS_ACCESS_KEY_ID and
# AWS_SECRET_ACCESS_KEY are environment variables in the current session.

require 'aws-sdk-s3'

if ARGV.count != 2
  STDERR.puts "Usage: archiver bucket_name file_to_be_archived\n"
  exit 1
end

bucket_name=ARGV[0]
upload_path=ARGV[1]

Aws.config.update({
  region: 'us-west-2',
  credentials: Aws::Credentials.new(ENV['AWS_ACCESS_KEY_ID'], ENV['AWS_SECRET_ACCESS_KEY'])
})

s3 = Aws::S3::Resource.new(region:'us-west-2')
obj = s3.bucket(bucket_name).object('key')
result = obj.upload_file(upload_path, {
  server_side_encryption: 'aws:kms',
  storage_class: 'STANDARD_IA',
})

print "Success? #{result}"
